---

name: sucky

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
    volumes:
      - ./plex:/config
      - /media/hdd1/data/media:/data/media
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./radarr:/config
      - /media/hdd1/data:/data
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./sonarr:/config
      - /media/hdd1/data:/data
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./sabnzbd:/config
      - /media/hdd1/data/usenet:/data/usenet
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    ports:
      - "5055:5055"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./jellyseerr:/app/config
    restart: unless-stopped

  recyclarr:
    container_name: recyclarr
    image: recyclarr/recyclarr:7
    user: 1000:1000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./recyclarr:/config

  umlautadaptarr:
    container_name: umlautadaptarr
    image: pcjones/umlautadaptarr:latest
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=true
      - SONARR__HOST=http://xxx.xxx.xxx.xxx:xxxx
      - SONARR__APIKEY=APIKEY
      - RADARR__ENABLED=true
      - RADARR__HOST=http://xxx.xxx.xxx.xxx:xxxx
      - RADARR__APIKEY=APIKEY
